export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_ERROR = 'FETCH_PRODUCT_ERROR';
export const FETCH_PRODUCT_PENDING = 'FETCH_PRODUCT_PENDING';
export const ADD_PRODUCT_TO_CART = 'ADD_PRODUCT_TO_CART';
